/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_minibae_Sound */

#ifndef _Included_org_minibae_Sound
#define _Included_org_minibae_Sound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_minibae_Sound
 * Method:    _newNativeSound
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Sound__1newNativeSound
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
