/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_minibae_Sound */

#ifndef _Included_org_minibae_Sound
#define _Included_org_minibae_Sound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_minibae_Sound
 * Method:    _newNativeSound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Sound__1newNativeSound
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_minibae_Sound
 * Method:    _loadSound
 * Signature: (ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Sound__1loadSound__ILjava_nio_ByteBuffer_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_minibae_Sound
 * Method:    _loadSound
 * Signature: (ILandroid/content/res/AssetManager;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Sound__1loadSound__ILandroid_content_res_AssetManager_2Ljava_lang_String_2
  (JNIEnv *, jobject, jint, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
