/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_minibae_Mixer */

#ifndef _Included_org_minibae_Mixer
#define _Included_org_minibae_Mixer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_minibae_Mixer
 * Method:    _newMixer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1newMixer
  (JNIEnv *, jclass);

/*
 * Class:     org_minibae_Mixer
 * Method:    _deleteMixer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_minibae_Mixer__1deleteMixer
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_minibae_Mixer
 * Method:    _openMixer
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_minibae_Mixer__1openMixer
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
