/**********
     TITLE: Graphic Widgets Library
   VERSION: 1.2.0
      TYPE: Code Library
    AUTHOR: Chris van Rensburg
 COPYRIGHT: 1996-2001 Beatnik, Inc. All Rights Reserved
**********/
isJavaScript1_1=typeof Image!=null;baseURL=window.location.href;baseURL=baseURL.substring(0,baseURL.lastIndexOf('/')+1);function Slider_getNotch(_a){return this.notches-(Math.floor((_a*this.notches)/(this.maxValue-this.minValue+1))+1)+1;}function Slider_setValue(_b){var _c=this;_b=Math.min(_c.maxValue,Math.max(_c.minValue,_b));if(_b!=_c.value){_c.value=_b;_c.update(_c.getNotch(_c.value));}}function Slider_update(_d){var _c=this;if(_d!=_c.currentNotch){var _e=_c.currentNotch;_c.currentNotch=_d;if(isJavaScript1_1){document[_c.objectName+'Notch'+_c.currentNotch].src=_c.nob.src;document[_c.objectName+'Notch'+_e].src=_c.back.src;}}}function Slider_mouseout(){this.blurTimeout=setTimeout(this.objectName+'.blur ()',250);}function Slider_mouseover(_d){var _c=this;
if(_c!=Slider_currentFocus&&Slider_currentFocus!=null)Slider_currentFocus.blur();if(_c.focused){clearTimeout(_c.blurTimeout);_c.update(_d);_c.value=_c.minValue+Math.round((_c.maxValue-_c.minValue)*(_c.notches-_c.currentNotch)/(_c.notches-1));eval(_c.onChange);}}function Slider_blur(){var _c=this;if(_c.focused){clearTimeout(_c.blurTimeout);if(isJavaScript1_1){var _f=_c.objectName+'Frame';document[_f+'TL'].src=_c.frameBlurTL.src;document[_f+'TR'].src=_c.frameBlurTR.src;document[_f+'HT'].src=_c.frameBlurH.src;document[_f+'VL'].src=_c.frameBlurV.src;document[_f+'VR'].src=_c.frameBlurV.src;document[_f+'BL'].src=_c.frameBlurBL.src;document[_f+'BR'].src=_c.frameBlurBR.src;document[_f+'HB'].src=_c.frameBlurH.src;}_c.focused=false;}Slider_currentFocus=null;}function Slider_focus(){var _c=this;if(_c!=Slider_currentFocus){if(Slider_currentFocus!=null)Slider_currentFocus.blur();Slider_currentFocus=_c;clearTimeout(_c.blurTimeout);if(isJavaScript1_1){var _f=_c.objectName+'Frame';document[_f+'TL'].src=_c.frameFocusTL.src;
document[_f+'TR'].src=_c.frameFocusTR.src;document[_f+'HT'].src=_c.frameFocusH.src;document[_f+'VL'].src=_c.frameFocusV.src;document[_f+'VR'].src=_c.frameFocusV.src;document[_f+'BL'].src=_c.frameFocusBL.src;document[_f+'BR'].src=_c.frameFocusBR.src;document[_f+'HB'].src=_c.frameFocusH.src;}_c.focused=true;}}function Slider_click(_d){if(!this.focused)this.focus();else this.blur();this.mouseover(_d);}function Slider(_g,_h,_i,_j,_k,_l,_m,_n,_o,_p){var _c=this;if(typeof _p!='string')_p='slider/';_c.objectName=_g;_c.onChange=_h;_c.minValue=_i;_c.maxValue=_j;_c.value=_k;_c.notches=_l;_c.width=_m;_c.height=_n;_c.frameWidth=_o;_c.imagesPath=_p;_c.getNotch=Slider_getNotch;_c.update=Slider_update;_c.mouseover=Slider_mouseover;_c.mouseout=Slider_mouseout;_c.click=Slider_click;_c.focus=Slider_focus;_c.blur=Slider_blur;_c.setValue=Slider_setValue;if(isJavaScript1_1){var _f=baseURL+_c.imagesPath;_c.frameBlurTL=new Image(_o,_o);_c.frameBlurTR=new Image(_o,_o);_c.frameBlurBL=new Image(_o,_o);_c.frameBlurBR=new Image(_o,_o);
_c.frameBlurH=new Image(_m,_o);_c.frameBlurV=new Image(_o,_n*_c.notches);_c.frameBlurTL.src=_f+'blur-tl.gif';_c.frameBlurTR.src=_f+'blur-tr.gif';_c.frameBlurBL.src=_f+'blur-bl.gif';_c.frameBlurBR.src=_f+'blur-br.gif';_c.frameBlurH.src=_f+'blur-h.gif';_c.frameBlurV.src=_f+'blur-v.gif';_c.frameFocusTL=new Image(_o,_o);_c.frameFocusTR=new Image(_o,_o);_c.frameFocusBL=new Image(_o,_o);_c.frameFocusBR=new Image(_o,_o);_c.frameFocusH=new Image(_m,_o);_c.frameFocusV=new Image(_o,_n*_l);_c.frameFocusTL.src=_f+'focus-tl.gif';_c.frameFocusTR.src=_f+'focus-tr.gif';_c.frameFocusBL.src=_f+'focus-bl.gif';_c.frameFocusBR.src=_f+'focus-br.gif';_c.frameFocusH.src=_f+'focus-h.gif';_c.frameFocusV.src=_f+'focus-v.gif';_c.nob=new Image(_m,_n);_c.nob.src=_f+'nob.gif';_c.back=new Image(_m,_n);_c.back.src=_f+'back.gif';}_c.currentNotch=_c.getNotch(_c.value);_c.focused=false;_c.blurTimeout=setTimeout('//',0);document.writeln('<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0>'+
'<TR><TD><IMG SRC="'+_p+'blur-tl.gif" WIDTH='+_o+' HEIGHT='+_o+' NAME="'+_g+'FrameTL"></TD><TD><IMG SRC="'+_p+'blur-h.gif" WIDTH='+_m+' HEIGHT='+_o+' NAME="'+_g+'FrameHT"></TD><TD><IMG SRC="'+_p+'blur-tr.gif" WIDTH='+_o+' HEIGHT='+_o+' NAME="'+_g+'FrameTR"></TD></TR>'+'<TR><TD><IMG SRC="'+_p+'blur-v.gif" WIDTH='+_o+' HEIGHT='+_n*_l+' NAME="'+_g+'FrameVL"></TD><TD>');for(var _q=1;_q<=_l;_q++){document.writeln('<A HREF="javascript://" ONCLICK="'+_g+'.click ('+_q+'); return false" ONMOUSEOVER="'+_g+'.mouseover ('+_q+')" ONMOUSEOUT="'+_g+'.mouseout ()"><IMG SRC="'+_p+((_q==_c.currentNotch)?'nob':'back')+'.gif" BORDER=0 HSPACE=0 VSPACE=0 WIDTH='+_m+' HEIGHT='+_n+' NAME="'+_g+'Notch'+_q+'"><BR></A>');}document.writeln('</TD><TD><IMG SRC="'+_p+'blur-v.gif" WIDTH='+_o+' HEIGHT='+_n*_l+' NAME="'+_g+'FrameVR"></TD></TR>'+'<TR><TD><IMG SRC="'+_p+'blur-bl.gif" WIDTH='+_o+' HEIGHT='+_o+' NAME="'+_g+'FrameBL"></TD><TD><IMG SRC="'+_p+'blur-h.gif" WIDTH='+_m+' HEIGHT='+_o+
' NAME="'+_g+'FrameHB"></TD><TD><IMG SRC="'+_p+'blur-br.gif" WIDTH='+_o+' HEIGHT='+_o+' NAME="'+_g+'FrameBR"></TD></TR>'+'</TABLE>');window[_g]=_c;}Slider_currentFocus=null;