/**********
     TITLE: Matrix Object
   VERSION: 1.2.0
      TYPE: Object Definition
    AUTHOR: Chris van Rensburg
 COPYRIGHT: 1996-2001 Beatnik, Inc. All Rights Reserved
**********/
function Matrix_a(_a,_b){this.segmentOver(_a,_b);this._c(this._d,this._e);}function Matrix_b(_a,_b){var _f=this;if(_a!=_f._g||_b!=_f._h){if(_a!=_f._g){if(_f._g!=0)document.images[_f._i+'PointerX-'+_f._g].src=_f._j.src;_f._g=_a;document.images[_f._i+'PointerX-'+_f._g].src=_f._k.src;_f._d=_f._l+(_f._g-1)*(_f._m/(_f._n-1));if(_f._o){_f._d=Math.round(_f._d)}document[_f._i+'Form'].valueX.value=_f._d;}if(_b!=_f._h){if(_f._h!=0)document.images[_f._i+'PointerY-'+_f._h].src=_f._p.src;_f._h=_b;document.images[_f._i+'PointerY-'+_f._h].src=_f._q.src;_f._e=_f._r+(_f._h-1)*(_f._s/(_f._t-1));if(_f._u)_f._e=Math.round(_f._e);document[_f._i+'Form'].valueY.value=_f._e;}window.status=this._v+' = '+this._d+'   :   '+this._w+' = '+this._e;}}function Matrix_c(){var _f=this,_x=_f._y/_f._n,_z=_f._A/_f._t,_B,_C,_D;
document.writeln('<MAP NAME="'+_f._i+'Imagemap">');_D=_f._A;for(var _E=1;_E<=_f._t;_E++){_C=0;for(var _F=1;_F<=_f._n;_F++){window.defaultStatus=_F+':'+_E;_B=' ('+_F+','+_E+')';document.writeln('<AREA'+' SHAPE=RECT'+' COORDS='+Math.round(_C)+','+Math.round(_D-_z)+','+Math.round(_C+_x)+','+Math.round(_D)+' HREF="javascript:'+_f._i+'.segmentClick'+_B+'"'+' ONCLICK="'+_f._i+'.segmentClick'+_B+'; return false"'+' ONMOUSEOVER="'+_f._i+'.segmentOver'+_B+'; return true"'+'>');_C+=_x;}_D-=_z;}document.writeln('</MAP>');document.writeln('<FORM NAME="'+_f._i+'Form">'+'<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 BGCOLOR=000000>'+'<TR VALIGN=CENTER>'+'<TD>'+'<TABLE HEIGHT='+_f._A+' BORDER=0 CELLSPACING=0 CELLPADDING=0>'+'<TR><TD ALIGN=RIGHT VALIGN=TOP><FONT SIZE=2 COLOR=FF0000>'+_f._s+'&nbsp;&nbsp;</FONT></TD></TR>'+'<TR><TD ALIGN=CENTER VALIGN=CENTER><FONT FACE="ARIAL,HELVETICA,VERDANA" COLOR=FFFFFF>'+_f._w+'</FONT>&nbsp;&nbsp;<BR><INPUT TYPE=text SIZE=5 NAME="valueY" VALUE=""></TD></TR>'+
'<TR><TD ALIGN=RIGHT VALIGN=BOTTOM><FONT SIZE=2 COLOR=FF0000>'+_f._r+'&nbsp;&nbsp;</FONT></TD></TR>'+'</TABLE>'+'</TD><TD>'+'<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 BGCOLOR=333333>');for(var _E=_f._t;_E>=1;_E--){document.writeln('<TR><TD><IMG SRC="images/black.gif" WIDTH='+_f._G+' HEIGHT='+_f._G+' NAME="'+_f._i+'PointerY-'+_E+'" BORDER=0 HSPACE=0 VSPACE=1></TD></TR>');}document.writeln('</TABLE>'+'</TD>'+'<TD><IMG SRC="images/matrix-bg.gif" WIDTH='+_f._y+' HEIGHT='+_f._A+' BORDER=0 HSPACE=3 VSPACE=3 USEMAP="#'+_f._i+'Imagemap"></TD>'+'</TR>'+'<TR VALIGN=CENTER ALIGN=CENTER><TD COLSPAN=2 ROWSPAN=2><IMG SRC="images/black.gif" WIDTH=1 HEIGHT=1 BORDER=0 HSPACE=0 VSPACE=0></TD><TD>'+'<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=0 BGCOLOR=333333><TR>');for(var _F=1;_F<=_f._n;_F++){document.writeln('<TD><IMG SRC="images/black.gif" WIDTH='+_f._H+' HEIGHT='+_f._H+' NAME="'+_f._i+'PointerX-'+_F+'" BORDER=0 HSPACE=1 VSPACE=0></TD>');}document.writeln('</TR></TABLE>'+'</TD></TR><TR VALIGN=CENTER ALIGN=CENTER>'+'<TD>'+
'<TABLE WIDTH='+_f._y+' BORDER=0 CELLSPACING=0 CELLPADDING=0><TR VALIGN=TOP>'+'<TD ALIGN=LEFT><FONT SIZE=2 COLOR=FF0000>'+_f._l+'</FONT></TD>'+'<TD ALIGN=CENTER><FONT FACE="ARIAL,HELVETICA,VERDANA" COLOR=FFFFFF>'+_f._v+'</FONT><BR><INPUT TYPE=text SIZE=5 NAME="valueX" VALUE=""></TD>'+'<TD ALIGN=RIGHT><FONT SIZE=2 COLOR=FF0000>'+_f._m+'</FONT></TD>'+'</TR></TABLE>'+'</TD>'+'</TR></TABLE>'+'</FORM>');}function Matrix(_i,_v,_w,_o,_u,_l,_m,_r,_s,_y,_A,_n,_t,_c){this._i=_i;this._v=_v;this._w=_w;this._o=_o;this._u=_u;this._l=_l;this._m=_m;this._r=_r;this._s=_s;this._y=_y;this._A=_A;this._n=_n;this._t=_t;this._c=_c;this._g=0;this._h=0;this._H=Math.floor((_y-(_n-1)*2)/_n);this._G=Math.floor((_A-(_t-1)*2)/_t);this._k=new Image(this._H,this._H);this._k.src='images/matrix-pointer-x.gif';this._j=new Image(this._H,this._H);this._j.src='images/black.gif';this._q=new Image(this._G,this._G);this._q.src='images/matrix-pointer-y.gif';this._p=new Image(this._G,this._G);this._p.src='images/black.gif';this._d=null;this._e=null;
this.segmentOver=Matrix_b;this.segmentClick=Matrix_a;this.generate=Matrix_c;window[_i]=this;}